### ISSUE TITLE
[new resource]: Introduction to Europeana APIs

### ISSUE THREAD

**Issue by vdritsou** [DARIAH-ERIC/dariah-campus#1110]
### Title of the resource

Introduction to Europeana APIs

### Resource type

Hosted Resource

### Authors, editors and contributors

Vicky Dritsou, Agiatis Benardou, Gustavo Candela, Sally Chambers, Alba Irollo, Toma Tasovac

### Topics (keywords)

Europeana, API, Query formulation, Information retrieval, JSON, JSON-LD, RDF/XML, Cultural Heritage

### Learning outcomes

Upon completion of this course, participants will: 
- have an understanding of Europeana APIs, the purpose each one serves and their features; 
- understand the use of the API key; 
- be familiarized with the supported formats; 
- be able to search and retrieve information by efficiently formulating queries and handling responses.

### Abstract

This course provides a comprehensive understanding of Europeana as a digital platform through a walkthrough of the APIs it offers. It provides the knowledge and skills to understand the functionality of these interfaces, the purpose they serve and the functionality they have, in order to exploit them by formulating efficient queries for cultural heritage information retrieval. Building on a fictional academic persona, Prof. Lorena, it delves into the APIs, exploring their features and providing familiarization with supported formats.

**Comment by VickyGarnett** [comment]
Hi Vicky - this is fine to proceed to drafting now.  If you could re-word Learning Outcome 3 a little, that would be good, because it's not clear to me what this means.  Also, we should have a chat about the tags at some point.  I don't think we can include all of them as new tags, but if there is one you feel very strongly about we can have a look at that.  Thanks!  :) VG
