### ISSUE TITLE
[new resource]: ELDAH Consent Form Wizard Tutorials

### ISSUE THREAD

**Issue by clariah-at** [DARIAH-ERIC/dariah-campus#214]
### Title of the resource

ELDAH Consent Form Wizard Tutorials

### Resource type

External Resource

### Authors, editors and contributors

Norbert Czirjak, Vanessa Hannesschläger, Pawel Kamocki, Sina Krottmaier, Walter Scholger

### Topics (keywords)

GDPR, consent, data protection,

### Learning outcomes

- learn the broad basics of the GDPR
- learn about principles of data processing
- learn about the rights of data subjects
- learn about GDPR exceptions for research and archiving

### Abstract

The aim of the CFW is to support humanities researchers within the European Union in obtaining valid consent for data processing in the context of their specific professional activity.
This tool will guide you through a questionnaire that will consequently generate a GDPR-compliant form for obtaining consent from data subjects, tailored to your specific purpose and the data categories you intend to collect. 
Please be aware that the validity of the generated output will be dependent on the truthfulness and accuracy of the input you provide. Honest and comprehensive answers will improve the quality of the results generated by the tool.

**Comment by VickyGarnett** [comment]
Hi there - the people in this resource have now been included, but I haven't yet added any of the tags.  The reason for this is that they will be very specific and I can't see any other resources needing them at this stage.  I wonder if instead we might apply 'Research ethics' as a tag instead?  I can see at least one other resource coming down the track that this tag will apply to, so it will get more traction.  Let me know and I'll add it, otherwise happy to discuss further :)  For now, though, you should have all you need to proceed with adding this resource.  Thanks - V
