### ISSUE TITLE
Using Netlify CMS with two branches

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#264]
### Bug report

@stefanprobst At the moment, Netlify CMS works for only from the campus.dariah.eu build, which is linked to the `main` branch. I would like the elexis branch to function as a staging area, i.e. I'd like the authors to be able to click on their resource in the staging area and get the CMS working from there. 

Apparently, on the Netlify side of things, this can be done by hacking the `config.js` to use the respective branch based on the URL match from which it is being called: https://github.com/netlify/netlify-cms/issues/3790#issuecomment-635920266 

Could we hack /src/cms/cms.config.ts to do the same —  use `main` by default, and then `elexis` if the user called the url which includes elexis (I'm previewing it on elexis.humanistika.org). 

This is super important for me us because we'll be doing a lot of committing and previewing over the next month in the ELEXIS project. And if this works for us smoothly, we can think of setting a staging version of the site permanently...

Please let me know what you think.

**Comment by ttasovac** [comment]
ok, i tried this: https://github.com/DARIAH-ERIC/dariah-campus/pull/272/commits/ecdb68783467b0a8b54ad66ab4f35f19c238f039 and then I merged it into the `elexis` branch but this still doesn't work as expected.

logging in on http://elexis.humanistika.org/admin gets stuck like this:

![Снимок экрана 2022-01-02 в 14 18 38](https://user-images.githubusercontent.com/5304839/147877120-447c4ec3-225c-4984-aaf9-8eb74b18af3d.png)

**Comment by ttasovac** [comment]
Ok, I hacked things a bit and I can now log in into https://elexis.humanistika.org/admin into our cms and it will correctly retrieve the elexis branch. We can save things in the cms, send them for review and publish them from the cms and they will all correctly be pushed to the elexis branch. 

The only remaining problem is that I don't know how to check the `baseUrl` dynamically from `EditLink.tsx` so that I can construct the link to point to the elexis.humanistika.org domain and not the campus.humanistika.org.

**Comment by stefanprobst** [comment]
should it be possible to change the branch at runtime (i.e. via query parameter)? otherwise it might be less hacky to set a different branch for the elexis deploy at build time (which can be done via the `NEXT_PUBLIC_GIT_BRANCH` environment variable).

the base url used in the `EditLink` component can also be set via built-time environment variable `NEXT_PUBLIC_BASE_URL` (or hardcoded [here](https://github.com/DARIAH-ERIC/dariah-campus/blob/main/config/site.config.ts#L14)).

if you are deploying with vercel, you should be able to set these env vars in the dashboard. if you deploy differently, note that the environment variables need to be available at build time.

**Comment by ttasovac** [comment]
https://github.com/DARIAH-ERIC/dariah-campus/commit/1f39bc8f7568e8be6ec3a1ac0cd0c9ec53708ece, https://github.com/DARIAH-ERIC/dariah-campus/commit/ec5b6e1bb665318faeddc52add237883b9315486 and https://github.com/DARIAH-ERIC/dariah-campus/commit/1f39bc8f7568e8be6ec3a1ac0cd0c9ec53708ece got rid of the hard-coded hacks for the elexis branch. this is now handled by the separate environmental variables on the Vercel side of things.
