### ISSUE TITLE
videos and starting time parameter

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#70]
Dear @stefanprobst,

@VickyGarnett discovered that some videos stopped working yesterday. It turns out it was those videos which as part of their id also had a starting time parameter.

I pushed https://github.com/DARIAH-ERIC/dariah-campus/commit/e28bfa4a0206ad2dffbe5fbfd0241eacef9ff911 to remove starting times as a temporary fix.

I'm not really sure these videos _needed_ the starting time parameter, but it's a very useful feature to have if we are including a longer youtube video, but want the user to start playing the video from a particular point.

This is not urgent so we can leave it for later.

**Comment by stefanprobst** [comment]
did these work before? the `id` property on the `VideoCard` component expects the id only -- or something that can be parsed as a query parameter, i.e. `id="GRd0lDpuNIA?t=1430s"` should have worked (note the `?` instead of the `&`).

EDIT: yes, that would have played but not actually set the start time -- the youtube embed url format takes a `start` instead of `t` query param, and expects number value, not string like "20s"

i'll add a separate `startTime` property to `VideoCard`

**Comment by ttasovac** [comment]
> i'll add a separate startTime property to VideoCard

perfect! that will be much cleaner and really great to have
