### ISSUE TITLE
[new resource]: Photogrammetry Tutorial

### ISSUE THREAD

**Issue by ehanscam** [DARIAH-ERIC/dariah-campus#976]
### Title of the resource

Photogrammetry Tutorial

### Resource type

External Resource

### Authors, editors and contributors

Romain Herault, Emily Hanscam

### Topics (keywords)

Training and education; photogrammetry

### Learning outcomes

After viewing the user will have a basic knowledge of how to use the Kiri Engine app on a mobile device in photogrammetry.

### Abstract

As part of the Linnaeus University course 'Interactive Design for Digital Humanities', lecturer Dr. Romain Herault explains how to use a mobile phone in photogrammetry.

https://play.lnu.se/media/t/0_ptrvp9y0

**Comment by VickyGarnett** [comment]
Hi @ehanscam - both authors are already in the system, and as we've discussed this is a good resource, so you can proceed to adding this on the CMS now.

As with the other resource you've proposed, I wouldn't use the tag 'training and education', as this is only for resources that discuss the topic of training and education.  Otherwise, everything is training and education.  Rather think about what the content of the video covers and use tags appropriately.

And again, you should also expand on the abstract a bit to give more info, and do likewise for the description of the resource in the 'Content' field.  What do people use this app for?  Which researchers or practitioners would this suit?  Where in a workflow might this fit?  That sort of thing.

Thanks!

Vicky

**Comment by ehanscam** [comment]
Hey @VickyGarnett I've gone back to the creator to ask for more details on both, let me know how I should update the text, I can't seem to get back into the original post. I'm also not sure what you mean by adding it on the CMS - are there guidelines anywhere? Thanks!

**Comment by VickyGarnett** [comment]
Apologies Emily, I thought you'd already been in the system for some reason!

Yes, there are guidelines, here: https://campus.dariah.eu/docs/using-the-content-management-system
The link to the CMS is in those guidelines, but you can also find it on https://campus.dariah.eu/admin

If you're stuck, let me know and we can arrange a quick call to go through it all.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
And there's no need to add more info to the proposal you've made above, just bear the comments in mind when drafting up the resource :)

**Comment by ehanscam** [comment]
Hey Vicky, I got more info from the creater and attempted to draft both in the cms. I submitted them for review, but I couldn't get the preview to load so I'm not sure if it was actually done correctly. For example, the Video Card option doesn't seem to work with LNU play.. so I just inserted the URL below under remote host. Hopefully all the info is there and it can be rearranged by someone who is more coding-literate :)

**Comment by VickyGarnett** [comment]
Hi @ehanscam - I can see the Pull Requests now, and have deployed the previews, which should be available shortly.  I'll continue the conversation in each of the pull requests now so you can see what changes need to be made and where :)

**Comment by VickyGarnett** [comment]
Resource has been published, so closing issue
