### ISSUE TITLE
[new resource]: Chroma Key Tutorial

### ISSUE THREAD

**Issue by ehanscam** [DARIAH-ERIC/dariah-campus#977]
### Title of the resource

Chroma Key Tutorial

### Resource type

None

### Authors, editors and contributors

Romain Herault, Emily Hanscam

### Topics (keywords)

Training and education

### Learning outcomes

Viewers learn how to use Power Director, an app available on Android and IOS with a powerful green screen editor. 

### Abstract

As part of the Linnaeus University Internative Design for Digital Humanities course, lecturer Dr Romain Herault explains how to use Power Director to edit video footage using a green screen.

https://play.lnu.se/media/t/0_c8n3sfbv

**Comment by VickyGarnett** [comment]
Hi @ehanscam - both authors are already in the system, and as we've discussed this is a good resource, so you can proceed to adding this on the CMS now.

Incidentally, I wouldn't use the tag 'training and education', as this is only for resources that discuss the topic of training and education.  Otherwise, everything is training and education.  Rather think about what the content of the video covers and use tags appropriately.

You should also expand on the abstract a bit to give more info, and do likewise for the description of the resource in the 'Content' field.  What do people use this app for?  Which researchers or practitioners would this suit?  Where in a workflow might this fit?  That sort of thing.

Thanks!

Vicky

**Comment by ehanscam** [comment]
hey @VickyGarnett just checking in on this one, I revised it when I fixed the photogrammetry tutorial entry - let me know if there is something else I can do!

**Comment by VickyGarnett** [comment]
Hi @ehanscam - thanks for the prod!  I was waiting to publish a load of resources from another contributor before I popped this one up, to try to mix them up a little.  I think this is good to go, so I'll publish that today and I might make either this or your other one the feature of this week's #TrainingTuesday tweet if you want to retweet that around :)

**Comment by ehanscam** [comment]
@VickyGarnett Fantastic! No worries, my colleagues were asking so I figured I'd check in. Oh and yes, definitely! I am not sure who is behind https://twitter.com/DHLNU, but I will see if I can identify them and nudge them to reactive the account.. if nothing else I'll retweet it from my personal twitter. Can you message me when the resource is up and the tweet is posted?

**Comment by VickyGarnett** [comment]
Resource published, closing issue
